version: '3.1'

services:
  redmine:
    image: redmine:3.4.4
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/redmine/usr/src/redmine/files:/usr/src/redmine/files

  db:
    image: mysql:5.7
#rewrite default command of image to add some parameters to support mutilanguage
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: redmine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mysql/var/lib/mysql:/var/lib/mysql

  ldap:
    image: "osixia/openldap:1.1.11"
    restart: always
    environment:
      LDAP_ORGANISATION: isid
      LDAP_DOMAIN: isid.com.cn
      LDAP_BASE_DN: isid.com.cn
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_OPENLDAP_UID: 0
      LDAP_OPENLDAP_GID: 0
      LDAP_TLS: "false"
      LDAP_CONFIG_PASSWORD: "admin"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/ldap/var/lib/ldap:/var/lib/ldap
      - ./data/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d

  phpldapadmin:
    image: "osixia/phpldapadmin:0.7.1"
    restart: always
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
#      - 6443:443
      - 6080:80
