version: '3.1'

services:
  ldap:
    image: "osixia/openldap:1.1.11"
    restart: always
    environment:
      LDAP_ORGANISATION: isid
      LDAP_DOMAIN: isid.com.cn
      LDAP_BASE_DN: isid.com.cn
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_OPENLDAP_UID: 0
      LDAP_OPENLDAP_GID: 0
      LDAP_TLS: "false"
      LDAP_CONFIG_PASSWORD: "admin"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ldap/var/lib/ldap:/var/lib/ldap
      - ./ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
    ports:
      - 389:389

  phpldapadmin:
    image: "osixia/phpldapadmin:0.7.1"
    restart: always
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
#      - 6443:443
      - 6080:80
